apiVersion: v1
kind: Pod
metadata:
  name: root-user-container
  namespace: k29
spec:
  containers:
  - image: nginx:1.18.0
    name: secured-container
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault