BOX_IMAGE = "ubuntu/focal64"
WORKER_COUNT = 1
HOST_IP_BASE = "192.168.56"
CONTROL_NODE_IP = "#{HOST_IP_BASE}.10"
POD_CIDR = "192.168.112.0/16"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE

  config.vm.define "kube-control-plane" do |node|
    node.vm.hostname = "kube-control-plane"
    node.vm.network :private_network, ip: "#{CONTROL_NODE_IP}"
    node.vm.provider :virtualbox do |vb|
      vb.name = "kube-control-plane"
      vb.memory = 2048
      vb.cpus = 2
    end
    node.vm.provision "shell", path: "../scripts/common.sh"
    node.vm.provision "shell", path: "../scripts/control-plane.sh", args: "#{CONTROL_NODE_IP} #{POD_CIDR}"
  end

  (1..WORKER_COUNT).each do |i|
    WORKER_NODE_IP = "#{HOST_IP_BASE}.#{i + 10}"

    config.vm.define "kube-worker-#{i}" do |node|
      node.vm.hostname = "kube-worker-#{i}"
      node.vm.network :private_network, ip: "#{WORKER_NODE_IP}"
      node.vm.provider :virtualbox do |vb|
        vb.name = "kube-worker-#{i}"
        vb.memory = 1024
        vb.cpus = 2
      end
      node.vm.provision "shell", path: "../scripts/common.sh"
      node.vm.provision "shell", path: "../scripts/worker.sh", args: "#{WORKER_NODE_IP}"
    end
  end

  config.vm.provision "shell",
    run: "always",
    inline: "swapoff -a"
end