apiVersion: v1
kind: Pod
metadata:
  name: network-call
  securityContext:
    appArmorProfile:
      type: Localhost
      localhostProfile: network-deny
spec:
  containers:
  - name: network-call
    image: alpine/curl:8.12.1
    command: ["sh", "-c", "while true; do ping -c 1 google.com; sleep 5; done"]
